/** Actual files on disk. Generated by scripts/write-download-manifest.mjs — do not hand-edit. */
export type ExportKind = "codeOnly" | "codebase" | "portable" | "android" | "apk";
export type ExportFile = { version: string; file: string; bytes: number; mtime: string };
export const EXPORTS: Record<ExportKind, ExportFile | null> = {
  "codeOnly": {
    "version": "v.080",
    "file": "crabby-beach-v.080-code.md",
    "bytes": 171670,
    "mtime": "2026-09-08T05:21:57.081Z"
  },
  "codebase": {
    "version": "v.060",
    "file": "crabby-beach-v.060-codebase.zip",
    "bytes": 30171645,
    "mtime": "2026-09-04T12:39:50.450Z"
  },
  "portable": {
    "version": "v.060",
    "file": "crabby-beach-v.060-portable.zip",
    "bytes": 7012093,
    "mtime": "2026-09-04T12:39:48.494Z"
  },
  "android": {
    "version": "v.060",
    "file": "crabby-beach-v.060-android.zip",
    "bytes": 7113694,
    "mtime": "2026-09-04T12:39:48.798Z"
  },
  "apk": {
    "version": "v.060",
    "file": "crabby-beach-v.060.apk",
    "bytes": 7848199,
    "mtime": "2026-09-04T12:40:11.930Z"
  }
};
