/** Actual files on disk. Generated by scripts/write-download-manifest.mjs — do not hand-edit. */
export type ExportKind = "codeOnly" | "codebase" | "portable" | "android" | "apk";
export type ExportFile = { version: string; file: string; bytes: number; mtime: string };
export const EXPORTS: Record<ExportKind, ExportFile | null> = {
  "codeOnly": {
    "version": "v.098",
    "file": "crabby-beach-v.098-code.md",
    "bytes": 181869,
    "mtime": "2026-09-10T14:46:13.808Z"
  },
  "codebase": {
    "version": "v.090",
    "file": "crabby-beach-v.090-codebase.zip",
    "bytes": 43436366,
    "mtime": "2026-09-10T14:04:50.088Z"
  },
  "portable": {
    "version": "v.090",
    "file": "crabby-beach-v.090-portable.zip",
    "bytes": 19025270,
    "mtime": "2026-09-10T14:04:47.256Z"
  },
  "android": {
    "version": "v.090",
    "file": "crabby-beach-v.090-android.zip",
    "bytes": 19127837,
    "mtime": "2026-09-10T14:04:47.816Z"
  },
  "apk": {
    "version": "v.090",
    "file": "crabby-beach-v.090.apk",
    "bytes": 19969497,
    "mtime": "2026-09-10T14:05:08.312Z"
  }
};
